Revised definitions of FITS extension keywords
nom-tam-fits/nom-tam-fits pull request #657
Opened 2024-08-14 07:36 UTC by attipaci

based on available documentation.

- Fix associated value types for extension keywords. They were all too often incorrect
- Add missing keywords for the MaxIm DL keyword convention.
- Add constants to define standard values where appropriate. 
- Edit standard header comment values
- Update Javadoc

2024-08-14 10:23 UTC, attipaci commented
@johnmurphyastro, please take a look at this PR to see if the keyword definitions (esp. in `MaxImDLExt` are now correct). Once you are satisfied, I will merge the PR, and release another release candidate (1.20.1-rc2) so we can test before the finalized 1.20.1 is shipped.

2024-08-14 13:15 UTC, johnmurphyastro commented
Hi,
The changes you have made to MaxImDLExt all look excellent to me.
I have found one new error:

FOCUSSZ(VALUE.REAL, "[um] focuser step size"),

should actually be:

*FOCUSSSZ(VALUE.REAL, "[um] focuser step size"),*

Three 'S' to represent (FOCU*S* *S*tep *S*ize).

Regards, John Murphy



On Wed, 14 Aug 2024 at 11:23, Attila Kovacs ***@***.***>
wrote:

> @johnmurphyastro <https://github.com/johnmurphyastro>, please take a look
> at this PR to see if the keyword definitions (esp. in MaxImDLExt are now
> correct). Once you are satisfied, I will merge the PR, and release another
> release candidate (1.20.1-rc2) so we can test before the finalized 1.20.1
> is shipped.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nom-tam-fits/nom-tam-fits/pull/657#issuecomment-2288386673>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANW5NWJACOMVNCRCPEILTDLZRMV2DAVCNFSM6AAAAABMPX7RMOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBYGM4DMNRXGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-14 13:18 UTC, johnmurphyastro reviewed
The changes you have made to MaxImDLExt all look excellent to me.
I have found one new error:
FOCUSSZ(VALUE.REAL, "[um] focuser step size"),
should actually be:
FOCUSSSZ(VALUE.REAL, "[um] focuser step size"),
Three 'S' to represent (FOCUS Step Size).

2024-08-14 13:21 UTC, attipaci commented
> FOCUSSSZ(VALUE.REAL, "[um] focuser step size"), Three 'S' to represent (FOCUS Step Size).

Thanks for spotting it. Corrected it and pushed...

2024-08-14 13:21 UTC, attipaci commented
I will need to add test coverage for the new code before I can merge. But it should be straightforward enough...

2024-08-14 14:27 UTC, johnmurphyastro commented
Hi,
CommonExt.java also looks great. Thank you!

Some extra entries that might be worth considering are:

This looks great to me. Some extra entries that might be worth considering:
SITENAME(VALUE.STRING, "observatory name"),
SITEELEV(VALUE.REAL, "elevation of the imaging site in meters"),

FOCUSER(VALUE.STRING, "focuser name"),
FOCNAME(VALUE.STRING, "focuser name"),
FWHEEL(VALUE.STRING, "filter wheel"),

SCALE(VALUE.REAL, "[arcsec/pixel] image scale"),
PIXSCALE(VALUE.REAL, "[arcsec/pixel] image scale"),

// Synonym of ANGLE
OBJCTROT(VALUE.REAL, "[deg] image angle"),

// Synonym of GAIN
GAINRAW(VALUE.REAL, "amplifier gain"),
// Synonym of EGAIN
GAINADU(VALUE.REAL, "[e/ADU] amplifier gain"),


Regards, John Murphy

On Wed, 14 Aug 2024 at 14:22, Attila Kovacs ***@***.***>
wrote:

> I will need to add test coverage for the new code before I can merge. But
> it should be straightforward enough...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nom-tam-fits/nom-tam-fits/pull/657#issuecomment-2288729730>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANW5NWI6BQJ7ADNCA73MIVLZRNKYPAVCNFSM6AAAAABMPX7RMOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBYG4ZDSNZTGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-14 16:58 UTC, johnmurphyastro commented
An example of a GAIN is 125

On Wed, 14 Aug 2024 at 17:55, John Murphy ***@***.***> wrote:

> GAIN is defined in NOAOExt.java, but that definition appears to be a
> synonym of EGAIN.
>
> The amateur camera software uses GAIN to record the camera gain setting
> (the astronomical camera equivalent of ISO).
>
> On Wed, 14 Aug 2024 at 17:47, Attila Kovacs ***@***.***>
> wrote:
>
>> OK, I added these too. Make sure my slight reinterpretation is correct. I
>> want to ask you to confirm the following:
>>
>> PIXSCALE(VALUE.REAL, "[arcsec/pixel] image scale"),
>>
>> My understanding is that this keyword describes the physical scale of the
>> detector array, not the scale of pixels in the image. (While the two are
>> usually identical, they can be different). Were it not so, the standard
>> CRDELTn keywords would do the job better (in a more standard) way, which
>> is why I think it adds information that CRDELTn does not provide...
>>
>> // Synonym of GAIN
>> GAINRAW(VALUE.REAL, "amplifier gain"),
>>
>> I don't think a GAIN keyword is defined anywhere yet. Should we add it
>> (it's a little too nondescript, as sometimes it may be a numerical factor,
>> or dB, or even a string such as 'HI'/'LOW'. I'm amenable to adding it,
>> provided there is consistent usage and/or it is well documented.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/nom-tam-fits/nom-tam-fits/pull/657#issuecomment-2289298176>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANW5NWJUDSCPAEYU2XGAEXLZROC3ZAVCNFSM6AAAAABMPX7RMOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBZGI4TQMJXGY>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-08-14 17:32 UTC, johnmurphyastro commented
So I agree that GAIN was a poor naming choice by the camera software, but
it stores an important value, and is used by all the amateur camera
software to record the camera gain setting. Its range starts from 0 (a poor
choice - 1 would make more sense!). It's typically used at values between 0
to at least 800. Although it is normally an integer value, it is sometimes
a string such as "Low".

Thinking about it, it would make sense to add GAIN to CommonExt since its
amateur usage differs from the NOAOExt definition.

CommonExt.*GAIN(VALUE.ANY, "ampifier gain")*

Personally I think the camera manufacturers should have used ISOSPEED, but
sadly they didn't go that way. Perhaps we should considerCommonExt.GAINRAW
as a synonym of ISOSPEED.

Sadly, I think SCALE and PIXSCALE are just synonyms for CRDELTn. SCALE and
PIXSCALE values change according to the binning.

Regards, John Murphy

On Wed, 14 Aug 2024 at 17:58, John Murphy ***@***.***> wrote:

> An example of a GAIN is 125
>
> On Wed, 14 Aug 2024 at 17:55, John Murphy ***@***.***>
> wrote:
>
>> GAIN is defined in NOAOExt.java, but that definition appears to be a
>> synonym of EGAIN.
>>
>> The amateur camera software uses GAIN to record the camera gain setting
>> (the astronomical camera equivalent of ISO).
>>
>> On Wed, 14 Aug 2024 at 17:47, Attila Kovacs ***@***.***>
>> wrote:
>>
>>> OK, I added these too. Make sure my slight reinterpretation is correct.
>>> I want to ask you to confirm the following:
>>>
>>> PIXSCALE(VALUE.REAL, "[arcsec/pixel] image scale"),
>>>
>>> My understanding is that this keyword describes the physical scale of
>>> the detector array, not the scale of pixels in the image. (While the two
>>> are usually identical, they can be different). Were it not so, the standard
>>> CRDELTn keywords would do the job better (in a more standard) way,
>>> which is why I think it adds information that CRDELTn does not
>>> provide...
>>>
>>> // Synonym of GAIN
>>> GAINRAW(VALUE.REAL, "amplifier gain"),
>>>
>>> I don't think a GAIN keyword is defined anywhere yet. Should we add it
>>> (it's a little too nondescript, as sometimes it may be a numerical factor,
>>> or dB, or even a string such as 'HI'/'LOW'. I'm amenable to adding it,
>>> provided there is consistent usage and/or it is well documented.
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/nom-tam-fits/nom-tam-fits/pull/657#issuecomment-2289298176>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/ANW5NWJUDSCPAEYU2XGAEXLZROC3ZAVCNFSM6AAAAABMPX7RMOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBZGI4TQMJXGY>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>

2024-08-14 18:21 UTC, attipaci commented
OK, pushed again. I noted that `SCALE` and `PIXSCALE` are redundant with `CDELTn`, and added `GAIN` (although, I still need to change the value type to ANY).

2024-08-14 18:57 UTC, johnmurphyastro commented
That all looks great. Thanks.
Would it be possible to add the following synonyms (or something similar) to nom.tam.fits.header.Synonyms.java ?

    ANGLE(CommonExt.ANGLE, CommonExt.OBJCTROT),
    EGAIN(SBFitsExt.EGAIN, CommonExt.GAINADU),
    FOCUSER(CommonExt.FOCUSER, CommonExt.FOCNAME),
    FOCUSPOS(MaxImDLExt.FOCUSPOS, CommonExt.FOCPOS),
    FOCUSTEM(MaxImDLExt.FOCUSTEM, CommonExt.FOCTEMP),
    ISOSPEED(MaxImDLExt.ISOSPEED, CommonExt.GAINRAW),
    XBINNING(SBFitsExt.XBINNING, CommonExt.CCDXBIN),
    YBINNING(SBFitsExt.YBINNING, CommonExt.CCDYBIN),
    PIXSCALE(CommonExt.PIXSCALE, CommonExt.SCALE),

    CLOUDCVR(CommonExt.CLOUDCVR, MaxImDLExt.AOCCLOUD),
    HUMIDITY(CommonExt.HUMIDITY, MaxImDLExt.AOCHUM, MaxImDLExt.BOLTHUM),
    DEWPOINT(CommonExt.DEWPOINT, MaxImDLExt.AOCDEW, MaxImDLExt.BOLTDEW),
    AMBTEMP(CommonExt.AMBTEMP, MaxImDLExt.AOCAMBT, MaxImDLExt.BOLTAMBT),
    WINDSPD(CommonExt.WINDSPD, MaxImDLExt.BOLTWIND), // MaxImDLExt.AOCWIND, uses different units
    WINDDIR(CommonExt.WINDDIR, MaxImDLExt.AOCWINDD),
    PRESSURE(CommonExt.PRESSURE, MaxImDLExt.AOCBAROM),

Regards, John Murphy

2024-08-14 18:58 UTC, attipaci commented
> Would it be possible to add the following synonyms (or something similar) to nom.tam.fits.header.Synonyms.java ?

Yes, of course. But tomorrow though... :-)

2024-08-15 09:34 UTC, johnmurphyastro requested changes
It all looks great. I have only spotted a few very minor issues in the comments in CommonExt.java
Line 52: the comment for ANGLE should say it is a Synonym of OBJCTROT, not ANGLE
Line 64: e..g should be e.g.
Line 93: itmay should be it may

SBFitsExt.java (unrelated to these changes)
Line 160: comment ends with the word "the"

2024-08-15 11:22 UTC, attipaci commented
Thanks John! I've made the corrections, and also gathered a bunch more commonly used FITS keywords from HEASARC etc.

Hopefully we are approaching a sense of reasonable completeness here for typical use.

2024-08-15 14:43 UTC, attipaci commented
@johnmurphyastro, Let me know if you are happy with the current state of things, or if anything is missing or needs correcting. Once all if good, I'll merge it to master and create a new release candidate.

2024-08-15 15:38 UTC, johnmurphyastro commented
Hi @attipaci 
I have only found one error:
```
/** Filter wheel position */
FWHEEL(VALUE.STRING, "filter wheel position"),
```
should be
```
/** Filter wheel position */
FWHEEL(VALUE.STRING, "filter wheel name"),
```

Example usage:
FWHEEL  = 'SBIG Filter Wheel'  / Filter Wheel name
FWHEEL  = 'Manual filter wheel' / Filter Wheel name 

Thanks, John Murphy

2024-08-15 16:56 UTC, merged